[build]
  command = "npm run build"
  publish = "out"  # Use "out" if you are using next export

[dev]
  command = "npm run dev"  # Optional: command to run during development

[functions]
  directory = "netlify/functions"  # Optional: directory for serverless functions